/**
 * MED-TSO SMS v1.1 — central KPI and dashboard configuration.
 * Change values here only when the approved methodology changes.
 */
const SMS_VERSION_ = '7.1';

const KPI_SHEETS_ = {
  SETTINGS: 'KPI_Settings',
  GUIDE: 'KPI Guide',
  RANKING: 'KPI_TSO_Ranking',
  MEMBER_RANKING: 'KPI_Member_Ranking',
  ATTENDANCE: 'KPI_Attendance',
  COVERAGE: 'KPI_TC_Coverage',
  TASKS: 'KPI_Task_Statistics',
  TASK_ISSUES: 'KPI_Task_Issues',
  DASHBOARD: 'Dashboard'
};

const KPI_DEFAULTS_ = {
  TSO: {
    ATTENDANCE_WEIGHT: 40,
    TC_COVERAGE_WEIGHT: 30,
    TASK_PARTICIPATION_WEIGHT: 30,
    TARGET_TECHNICAL_COMMITTEES: 5,
    TARGET_TASK_ASSIGNMENTS: 3
  },
  MEMBER: {
    ATTENDANCE_WEIGHT: 40,
    MEMBERSHIP_WEIGHT: 40,
    LEADERSHIP_WEIGHT: 20,
    TARGET_COMMITTEES: 3,
    CHAIRMAN_SCORE: 100,
    VICE_CHAIRMAN_SCORE: 75,
    TECHNICAL_SECRETARIAT_SCORE: 60,
    SPOC_SCORE: 50
  },
  COMMITTEE_HEALTH: {
    ATTENDANCE_WEIGHT: 40,
    TSO_COVERAGE_WEIGHT: 30,
    TASK_ACTIVITY_WEIGHT: 30,
    HEALTHY_THRESHOLD: 80,
    ATTENTION_THRESHOLD: 60
  },
  DASHBOARD_TOP_N: 10,
  INCLUDE_COMPLETED_MEETINGS_ONLY: true
};
